[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Note: Set these in Netlify environment settings
# Required environment variables:
# - UNSPLASH_ACCESS_KEY
# - GROQ_API_KEY
